export type PortfolioCategory = 'neo-japones' | 'neo-tradicional' | 'cover-up' | 'realismo' | 'arte'

export interface PortfolioItem {
  src: string
  category: PortfolioCategory
  alt: string
}

export const categoryLabels: Record<PortfolioCategory, string> = {
  'neo-japones': 'Neo Japonés',
  'neo-tradicional': 'Neo Tradicional',
  'cover-up': 'Cover-ups',
  'realismo': 'Realismo',
  'arte': 'Arte',
}

export const portfolioItems: PortfolioItem[] = [
  // Neo Japonés
  { src: '/portfolio/neo-japanese/cat.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/daruma1.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/daruma2.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/daruma3.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/daruma4.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/daruma5.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/dragon1.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/dragon2.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/fenix.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/fenix2.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/fenix3.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/foodog.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/geisha.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/geisha2.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/hannya.JPG', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/hannya2.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/koi1.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/koi2.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/koi3.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/mangasnake1.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/mangasnake2.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/mangasnake3.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/mangasnake4.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/octupusbackpiece.JPG', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/templo.png', category: 'neo-japones', alt: 'Neo japonés' },
  { src: '/portfolio/neo-japanese/tiger.png', category: 'neo-japones', alt: 'Neo japonés' },

  // Neo Tradicional
  { src: '/portfolio/neo-tradicional/cat.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/chica.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/chica2.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/chica3.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/chica4.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/chica5.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/creaturaviviente.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/creaturaviviente2.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/dog.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/dog2.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/moth.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/paisaje.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/paisaje2.png', category: 'neo-tradicional', alt: 'Neo tradicional' },
  { src: '/portfolio/neo-tradicional/querubin.png', category: 'neo-tradicional', alt: 'Neo tradicional' },

  // Realismo
  { src: '/portfolio/neo-realism/dossatiros.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/jacob1.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/jacob2.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/jacob3.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/jesus1.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/jesus2.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/jesus3.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/jesus4.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/jesushealed.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/miguelvssatan1.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/miguelvssatan2.png', category: 'realismo', alt: 'Realismo' },
  { src: '/portfolio/neo-realism/miguelvssatan3.png', category: 'realismo', alt: 'Realismo' },

  // Cover-ups
  { src: '/portfolio/cover-ups/arbolcherries.png', category: 'cover-up', alt: 'Cover-up' },
  { src: '/portfolio/cover-ups/arbolcherries2.png', category: 'cover-up', alt: 'Cover-up' },
  { src: '/portfolio/cover-ups/arbolcherries3.png', category: 'cover-up', alt: 'Cover-up' },
  { src: '/portfolio/cover-ups/dragoncover1.png', category: 'cover-up', alt: 'Cover-up' },
  { src: '/portfolio/cover-ups/dragoncover2.png', category: 'cover-up', alt: 'Cover-up' },
  { src: '/portfolio/cover-ups/dragoncover3.png', category: 'cover-up', alt: 'Cover-up' },
  { src: '/portfolio/cover-ups/dragoncover4.png', category: 'cover-up', alt: 'Cover-up' },
  { src: '/portfolio/cover-ups/dragoncover5.png', category: 'cover-up', alt: 'Cover-up' },
  { src: '/portfolio/cover-ups/mangacover1.png', category: 'cover-up', alt: 'Cover-up manga' },
  { src: '/portfolio/cover-ups/mangacover2.png', category: 'cover-up', alt: 'Cover-up manga' },
  { src: '/portfolio/cover-ups/mangacover3.png', category: 'cover-up', alt: 'Cover-up manga' },
  { src: '/portfolio/cover-ups/mangacover4.png', category: 'cover-up', alt: 'Cover-up manga' },
  { src: '/portfolio/cover-ups/mangacover5.png', category: 'cover-up', alt: 'Cover-up manga' },
  { src: '/portfolio/cover-ups/mangacover6.png', category: 'cover-up', alt: 'Cover-up manga' },
  { src: '/portfolio/cover-ups/mangadragon1.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon2.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon3.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon4.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon5.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon6.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon7.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon8.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon9.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon10.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon11.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon12.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon13.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon14.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon15.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon16.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/mangadragon17.png', category: 'cover-up', alt: 'Cover-up manga dragón' },
  { src: '/portfolio/cover-ups/pechocuervo.png', category: 'cover-up', alt: 'Cover-up pecho' },
  { src: '/portfolio/cover-ups/pechocuervo2.png', category: 'cover-up', alt: 'Cover-up pecho' },
  { src: '/portfolio/cover-ups/pechocuervo3.png', category: 'cover-up', alt: 'Cover-up pecho' },
  { src: '/portfolio/cover-ups/perrocherries.png', category: 'cover-up', alt: 'Cover-up' },
  { src: '/portfolio/cover-ups/perrocherries2.png', category: 'cover-up', alt: 'Cover-up' },
  { src: '/portfolio/cover-ups/perrocherries3.png', category: 'cover-up', alt: 'Cover-up' },

  // Arte
  { src: '/portfolio/Art/chicaconpajaros.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/chicayaguila1.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/chicayaguila2.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/dragonytigre1.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/dragonytigre2.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/dragonytigre3.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/dragonytigre4.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/dragonytigre5.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/dragonytigre6.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/dragonytigre7.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/dragonytigre8.JPG', category: 'arte', alt: 'Arte' },
  { src: '/portfolio/Art/dragonytigre9.JPG', category: 'arte', alt: 'Arte' },
]

export const heroImages = [
  '/portfolio/hero/DSC00259.jpg',
  '/portfolio/hero/DSC05442.JPG',
  '/portfolio/hero/DSC06469.JPG',
  '/portfolio/hero/DSC08674.JPG',
  '/portfolio/hero/DSC08889.JPG',
  '/portfolio/hero/DSC08891.JPG',
]
